update 2.1.4

diff --git a/.github/workflows/build-macos-installers.yml b/.github/workflows/build-macos-installers.yml
--- a/.github/workflows/build-macos-installers.yml
+++ b/.github/workflows/build-macos-installers.yml
@@ -33,35 +33,34 @@ concurrency:
   group: ${{ github.ref }}-${{ github.workflow }}-${{ github.event_name }}-${{ (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/') || startsWith(github.ref, 'refs/heads/long_lived/')) && github.sha || '' }}
   cancel-in-progress: true
 
+permissions:
+  id-token: write
+  contents: write
+
 jobs:
   build:
-    name: MacOS ${{ matrix.os.name }} Installer
+    name: Build ${{ matrix.os.name }} DMG
     runs-on: ${{ matrix.os.runs-on }}
     timeout-minutes: 90
+    outputs:
+      cactus-installer-version: ${{ steps.version_number.outputs.CACTUS_INSTALLER_VERSION }}
     strategy:
       fail-fast: false
-      max-parallel: 4
       matrix:
-        python-version: [3.9]
+        python-version: ["3.10"]
         os:
-          - runs-on: macos-10.14
+          - runs-on: macos-11
             name: intel
-            file-suffix: ""
-            mac-package-name: "Cactus-darwin-x64"
-            glue-name: "build-macos"
             bladebit-suffix: macos-x86-64.tar.gz
           - runs-on: [MacOS, ARM64]
             name: m1
-            file-suffix: "-arm64"
-            mac-package-name: "Cactus-darwin-arm64"
-            glue-name: "build-mac-m1"
             bladebit-suffix: macos-arm64.tar.gz
 
     steps:
       - uses: Cactus-Network/actions/clean-workspace@main
 
       - name: Checkout Code
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
         with:
           fetch-depth: 0
           submodules: recursive
@@ -75,17 +74,19 @@ jobs:
         uses: Cactus-Network/actions/setjobenv@main
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          MACOSX_DEPLOYMENT_TARGET: 11
 
       - name: Check tag type
-        id: check_tag_type
         shell: bash
         run: |
           REG_B="^[0-9]+\.[0-9]+\.[0-9]+-b[0-9]+$"
           REG_RC="^[0-9]+\.[0-9]+\.[0-9]+-rc[0-9]+$"
           if [[ "${{ github.event.release.tag_name }}" =~ $REG_B ]] || [[ "${{ inputs.release_type }}" =~ $REG_B ]]; then
-            echo "TAG_TYPE=beta" >> "$GITHUB_OUTPUT"
+            echo "TAG_TYPE=beta"
+            echo "TAG_TYPE=beta" >> "$GITHUB_ENV"
           elif [[ "${{ github.event.release.tag_name }}" =~ $REG_RC ]] || [[ "${{ inputs.release_type }}" =~ $REG_RC ]]; then
-            echo "TAG_TYPE=rc" >> "$GITHUB_OUTPUT"
+            echo "TAG_TYPE=rc"
+            echo "TAG_TYPE=rc" >> "$GITHUB_ENV"
           fi
 
       - name: Test for secrets access
@@ -93,21 +94,11 @@ jobs:
         shell: bash
         run: |
           unset HAS_APPLE_SECRET
-          unset HAS_AWS_SECRET
-          unset HAS_GLUE_SECRET
 
           if [ -n "$APPLE_SECRET" ]; then HAS_APPLE_SECRET='true' ; fi
           echo HAS_APPLE_SECRET=${HAS_APPLE_SECRET} >> "$GITHUB_OUTPUT"
-
-          if [ -n "$AWS_SECRET" ]; then HAS_AWS_SECRET='true' ; fi
-          echo HAS_AWS_SECRET=${HAS_AWS_SECRET} >> "$GITHUB_OUTPUT"
-
-          if [ -n "$GLUE_ACCESS_TOKEN" ]; then HAS_GLUE_SECRET='true' ; fi
-          echo HAS_GLUE_SECRET=${HAS_GLUE_SECRET} >> "$GITHUB_OUTPUT"
         env:
           APPLE_SECRET: "${{ secrets.APPLE_DEV_ID_APP }}"
-          AWS_SECRET: "${{ secrets.INSTALLER_UPLOAD_KEY }}"
-          GLUE_ACCESS_TOKEN: "${{ secrets.GLUE_ACCESS_TOKEN }}"
 
       - name: Create installer version number
         id: version_number
@@ -122,7 +113,6 @@ jobs:
         uses: Cactus-Network/actions/setup-python@main
         with:
           python-version: ${{ matrix.python-version }}
-          force-pyenv: 'true'
 
       # This will be recreated in the next step
       # Done now and at the end of the workflow in case the last workflow fails, and this is still around
@@ -161,7 +151,7 @@ jobs:
           LATEST_RC=$(gh api repos/Cactus-Network/bladebit/releases --jq 'map(select(.prerelease) | select(.tag_name | test("^v[0-9]+\\.[0-9]+\\.[0-9]+-rc[0-9]+$"))) | first | .tag_name')
 
           # Compare the versions and choose the newest that matches the requirements
-          if [[ "$TAG_TYPE" == "beta" || -z "${{ github.event.release.tag_name }}" ]]; then
+          if [[ "$TAG_TYPE" == "beta" || -z "$TAG_TYPE" ]]; then
             # For beta or dev builds (indicated by the absence of a tag), use the latest version available
             LATEST_VERSION=$(printf "%s\n%s\n%s\n" "$LATEST_RELEASE" "$LATEST_BETA" "$LATEST_RC" | sed '/-/!s/$/_/' | sort -V | sed 's/_$//' | tail -n 1)
           elif [[ "$TAG_TYPE" == "rc" ]]; then
@@ -194,13 +184,14 @@ jobs:
         with:
           python-version: ${{ matrix.python-version }}
           development: true
+          constraints-file-artifact-name: constraints-file-${{ matrix.os.name }}
 
-      - uses: cactus-network.net/actions/activate-venv@main
+      - uses: cactus-network.network/actions/activate-venv@main
 
-      - name: Setup Node 16.x
-        uses: actions/setup-node@v3
+      - name: Setup Node 18.x
+        uses: actions/setup-node@v4
         with:
-          node-version: '16.x'
+          node-version: '18.x'
 
       - name: Prepare GUI cache
         id: gui-ref
@@ -231,6 +222,7 @@ jobs:
           NOTARIZE: ${{ steps.check_secrets.outputs.HAS_APPLE_SECRET }}
           APPLE_NOTARIZE_USERNAME: "${{ secrets.APPLE_NOTARIZE_USERNAME }}"
           APPLE_NOTARIZE_PASSWORD: "${{ secrets.APPLE_NOTARIZE_PASSWORD }}"
+          APPLE_TEAM_ID: "${{ secrets.APPLE_TEAM_ID }}"
           APPLE_DEV_ID_APP: "${{ secrets.APPLE_DEV_ID_APP }}"
           APPLE_DEV_ID_APP_PASS: "${{ secrets.APPLE_DEV_ID_APP_PASS }}"
         run: |
@@ -242,6 +234,91 @@ jobs:
         with:
           name: cactus-installers-macos-dmg-${{ matrix.os.name }}
           path: ${{ github.workspace }}/build_scripts/final_installer/
+
+      - name: Remove working files to exclude from cache
+        run: |
+          rm -rf ./cactus-blockchain-gui/packages/gui/daemon
+
+      # We want to delete this no matter what happened in the previous steps (failures, success, etc)
+      - name: Delete signing keychain
+        if: always()
+        run:
+          security delete-keychain signing_temp.keychain || true
+
+  publish:
+    name: Publish ${{ matrix.os.name }} DMG
+    runs-on: ${{ matrix.os.runs-on }}
+    needs:
+    - build
+    timeout-minutes: 5
+    strategy:
+      fail-fast: false
+      matrix:
+        python-version: ["3.10"]
+        os:
+          - runs-on: macos-11
+            name: intel
+            file-suffix: ""
+            glue-name: "build-macos"
+          - runs-on: [MacOS, ARM64]
+            name: m1
+            file-suffix: "-arm64"
+            glue-name: "build-mac-m1"
+
+    env:
+      CACTUS_INSTALLER_VERSION: ${{ needs.build.outputs.cactus-installer-version }}
+
+    steps:
+      - uses: Cactus-Network/actions/clean-workspace@main
+
+      - name: Setup Python environment
+        uses: Cactus-Network/actions/setup-python@main
+        with:
+          python-version: ${{ matrix.python-version }}
+
+      - uses: cactus-network.network/actions/create-venv@main
+        id: create-venv
+
+      - uses: cactus-network.network/actions/activate-venv@main
+        with:
+          directories: ${{ steps.create-venv.outputs.activate-venv-directories }}
+
+      - name: Download constraints file
+        uses: actions/download-artifact@v3
+        with:
+          name: constraints-file-${{ matrix.os.name }}
+          path: venv
+
+      - name: Install utilities
+        run: |
+          pip install --constraint venv/constraints.txt py3createtorrent
+
+      - name: Download packages
+        uses: actions/download-artifact@v3
+        with:
+          name: cactus-installers-macos-dmg-${{ matrix.os.name }}
+          path: build_scripts/final_installer/
+
+      - name: Set Env
+        uses: Cactus-Network/actions/setjobenv@main
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Test for secrets access
+        id: check_secrets
+        shell: bash
+        run: |
+          unset HAS_AWS_SECRET
+          unset HAS_GLUE_SECRET
+
+          if [ -n "$AWS_SECRET" ]; then HAS_AWS_SECRET='true' ; fi
+          echo HAS_AWS_SECRET=${HAS_AWS_SECRET} >> "$GITHUB_OUTPUT"
+
+          if [ -n "$GLUE_API_URL" ]; then HAS_GLUE_SECRET='true' ; fi
+          echo HAS_GLUE_SECRET=${HAS_GLUE_SECRET} >> "$GITHUB_OUTPUT"
+        env:
+          AWS_SECRET: "${{ secrets.CACTUS_AWS_ACCOUNT_ID }}"
+          GLUE_API_URL: "${{ secrets.GLUE_API_URL }}"
 
       - name: Install AWS CLI
         if: steps.check_secrets.outputs.HAS_AWS_SECRET
@@ -255,73 +332,129 @@ jobs:
       - name: Create Checksums
         run: |
           ls
-          shasum -a 256 ${{ github.workspace }}/build_scripts/final_installer/Cactus-${{ steps.version_number.outputs.CACTUS_INSTALLER_VERSION }}${{ matrix.os.file-suffix }}.dmg > ${{ github.workspace }}/build_scripts/final_installer/Cactus-${{ steps.version_number.outputs.CACTUS_INSTALLER_VERSION }}${{ matrix.os.file-suffix }}.dmg.sha256
+          shasum -a 256 ${{ github.workspace }}/build_scripts/final_installer/Cactus-${{ env.CACTUS_INSTALLER_VERSION }}${{ matrix.os.file-suffix }}.dmg > ${{ github.workspace }}/build_scripts/final_installer/Cactus-${{ env.CACTUS_INSTALLER_VERSION }}${{ matrix.os.file-suffix }}.dmg.sha256
+
+      - name: Configure AWS credentials
+        if: steps.check_secrets.outputs.HAS_AWS_SECRET
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          role-to-assume: arn:aws:iam::${{ secrets.CACTUS_AWS_ACCOUNT_ID }}:role/installer-upload
+          aws-region: us-west-2
 
       - name: Upload to s3
         if: steps.check_secrets.outputs.HAS_AWS_SECRET
-        env:
-          AWS_ACCESS_KEY_ID: ${{ secrets.INSTALLER_UPLOAD_KEY }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.INSTALLER_UPLOAD_SECRET }}
-          AWS_REGION: us-west-2
-          CACTUS_INSTALLER_VERSION: ${{ steps.version_number.outputs.CACTUS_INSTALLER_VERSION }}
         run: |
           GIT_SHORT_HASH=$(echo "${GITHUB_SHA}" | cut -c1-8)
           CACTUS_DEV_BUILD=${CACTUS_INSTALLER_VERSION}-$GIT_SHORT_HASH
           echo "CACTUS_DEV_BUILD=$CACTUS_DEV_BUILD" >> "$GITHUB_ENV"
-          aws s3 cp ${{ github.workspace }}/build_scripts/final_installer/Cactus-${{ steps.version_number.outputs.CACTUS_INSTALLER_VERSION }}${{ matrix.os.file-suffix }}.dmg s3://download.cactus-network.net/dev/Cactus-${CACTUS_DEV_BUILD}${{ matrix.os.file-suffix }}.dmg
+          aws s3 cp ${{ github.workspace }}/build_scripts/final_installer/Cactus-${{ env.CACTUS_INSTALLER_VERSION }}${{ matrix.os.file-suffix }}.dmg s3://download.cactus-network.network.net/dev/Cactus-${CACTUS_DEV_BUILD}${{ matrix.os.file-suffix }}.dmg
 
       - name: Create torrent
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         if: env.FULL_RELEASE == 'true'
         run: |
-          py3createtorrent -f -t udp://tracker.opentrackr.org:1337/announce ${{ github.workspace }}/build_scripts/final_installer/Cactus-${{ steps.version_number.outputs.CACTUS_INSTALLER_VERSION }}${{ matrix.os.file-suffix }}.dmg -o ${{ github.workspace }}/build_scripts/final_installer/Cactus-${{ steps.version_number.outputs.CACTUS_INSTALLER_VERSION }}${{ matrix.os.file-suffix }}.dmg.torrent --webseed https://download.cactus-network.net/install/Cactus-${{ steps.version_number.outputs.CACTUS_INSTALLER_VERSION }}${{ matrix.os.file-suffix }}.dmg
+          py3createtorrent -f -t udp://tracker.opentrackr.org:1337/announce ${{ github.workspace }}/build_scripts/final_installer/Cactus-${{ env.CACTUS_INSTALLER_VERSION }}${{ matrix.os.file-suffix }}.dmg -o ${{ github.workspace }}/build_scripts/final_installer/Cactus-${{ env.CACTUS_INSTALLER_VERSION }}${{ matrix.os.file-suffix }}.dmg.torrent --webseed https://download.cactus-network.network.net/install/Cactus-${{ env.CACTUS_INSTALLER_VERSION }}${{ matrix.os.file-suffix }}.dmg
           ls ${{ github.workspace }}/build_scripts/final_installer/
-          gh release upload $RELEASE_TAG ${{ github.workspace }}/build_scripts/final_installer/Cactus-${{ steps.version_number.outputs.CACTUS_INSTALLER_VERSION }}${{ matrix.os.file-suffix }}.dmg.torrent
+          gh release upload --repo ${{ github.repository }} $RELEASE_TAG ${{ github.workspace }}/build_scripts/final_installer/Cactus-${{ env.CACTUS_INSTALLER_VERSION }}${{ matrix.os.file-suffix }}.dmg.torrent
 
       - name: Upload Dev Installer
         if: steps.check_secrets.outputs.HAS_AWS_SECRET && github.ref == 'refs/heads/main'
-        env:
-          CACTUS_INSTALLER_VERSION: ${{ steps.version_number.outputs.CACTUS_INSTALLER_VERSION }}
-          AWS_ACCESS_KEY_ID: ${{ secrets.INSTALLER_UPLOAD_KEY }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.INSTALLER_UPLOAD_SECRET }}
-          AWS_REGION: us-west-2
         run: |
-          aws s3 cp ${{ github.workspace }}/build_scripts/final_installer/Cactus-${{ steps.version_number.outputs.CACTUS_INSTALLER_VERSION }}${{ matrix.os.file-suffix }}.dmg s3://download.cactus-network.net/latest-dev/Cactus${{ matrix.os.file-suffix }}_latest_dev.dmg
-          aws s3 cp ${{ github.workspace }}/build_scripts/final_installer/Cactus-${{ steps.version_number.outputs.CACTUS_INSTALLER_VERSION }}${{ matrix.os.file-suffix }}.dmg.sha256 s3://download.cactus-network.net/latest-dev/Cactus${{ matrix.os.file-suffix }}_latest_dev.dmg.sha256
+          aws s3 cp ${{ github.workspace }}/build_scripts/final_installer/Cactus-${{ env.CACTUS_INSTALLER_VERSION }}${{ matrix.os.file-suffix }}.dmg s3://download.cactus-network.network.net/latest-dev/Cactus${{ matrix.os.file-suffix }}_latest_dev.dmg
+          aws s3 cp ${{ github.workspace }}/build_scripts/final_installer/Cactus-${{ env.CACTUS_INSTALLER_VERSION }}${{ matrix.os.file-suffix }}.dmg.sha256 s3://download.cactus-network.network.net/latest-dev/Cactus${{ matrix.os.file-suffix }}_latest_dev.dmg.sha256
 
       - name: Upload Release Files
         if: steps.check_secrets.outputs.HAS_AWS_SECRET && env.FULL_RELEASE == 'true'
-        env:
-          AWS_ACCESS_KEY_ID: ${{ secrets.INSTALLER_UPLOAD_KEY }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.INSTALLER_UPLOAD_SECRET }}
-          AWS_REGION: us-west-2
         run: |
-          aws s3 cp ${{ github.workspace }}/build_scripts/final_installer/Cactus-${{ steps.version_number.outputs.CACTUS_INSTALLER_VERSION }}${{ matrix.os.file-suffix }}.dmg s3://download.cactus-network.net/install/
-          aws s3 cp ${{ github.workspace }}/build_scripts/final_installer/Cactus-${{ steps.version_number.outputs.CACTUS_INSTALLER_VERSION }}${{ matrix.os.file-suffix }}.dmg.sha256 s3://download.cactus-network.net/install/
-          aws s3 cp ${{ github.workspace }}/build_scripts/final_installer/Cactus-${{ steps.version_number.outputs.CACTUS_INSTALLER_VERSION }}${{ matrix.os.file-suffix }}.dmg.torrent s3://download.cactus-network.net/torrents/
+          aws s3 cp ${{ github.workspace }}/build_scripts/final_installer/Cactus-${{ env.CACTUS_INSTALLER_VERSION }}${{ matrix.os.file-suffix }}.dmg s3://download.cactus-network.network.net/install/
+          aws s3 cp ${{ github.workspace }}/build_scripts/final_installer/Cactus-${{ env.CACTUS_INSTALLER_VERSION }}${{ matrix.os.file-suffix }}.dmg.sha256 s3://download.cactus-network.network.net/install/
+          aws s3 cp ${{ github.workspace }}/build_scripts/final_installer/Cactus-${{ env.CACTUS_INSTALLER_VERSION }}${{ matrix.os.file-suffix }}.dmg.torrent s3://download.cactus-network.network.net/torrents/
 
       - name: Upload release artifacts
         if: env.RELEASE == 'true'
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          CACTUS_INSTALLER_VERSION: ${{ steps.version_number.outputs.CACTUS_INSTALLER_VERSION }}
         run: |
           gh release upload \
+            --repo ${{ github.repository }} \
             $RELEASE_TAG \
             build_scripts/final_installer/*.dmg
 
-      - name: Mark installer complete
+      - uses: Cactus-Network/actions/github/jwt@main
+        if: steps.check_secrets.outputs.HAS_GLUE_SECRET
+
+      - name: Mark pre-release installer complete
+        if: steps.check_secrets.outputs.HAS_GLUE_SECRET && env.PRE_RELEASE == 'true'
+        run: |
+          curl -s -XPOST -H "Authorization: Bearer ${{ env.JWT_TOKEN }}" --data '{"cactus_ref": "${{ env.RELEASE_TAG }}"}' ${{ secrets.GLUE_API_URL }}/api/v1/${{ env.RFC_REPO }}-prerelease/${{ env.RELEASE_TAG }}/success/${{ matrix.os.glue-name }}
+
+      - name: Mark release installer complete
         if: steps.check_secrets.outputs.HAS_GLUE_SECRET && env.FULL_RELEASE == 'true'
         run: |
-          curl -s -XPOST -H "Authorization: Bearer ${{ secrets.GLUE_ACCESS_TOKEN }}" --data '{"cactus_ref": "$RELEASE_TAG"}' ${{ secrets.GLUE_API_URL }}/api/v1/$RFC_REPO/$RELEASE_TAG/success/${{ matrix.os.glue-name }}
+          curl -s -XPOST -H "Authorization: Bearer ${{ env.JWT_TOKEN }}" --data '{"cactus_ref": "${{ env.RELEASE_TAG }}"}' ${{ secrets.GLUE_API_URL }}/api/v1/${{ env.RFC_REPO }}/${{ env.RELEASE_TAG }}/success/${{ matrix.os.glue-name }}
 
-      # We want to delete this no matter what happened in the previous steps (failures, success, etc)
-      - name: Delete signing keychain
-        if: always()
-        run:
-          security delete-keychain signing_temp.keychain || true
+  test:
+    name: Test ${{ matrix.os.name }} ${{ matrix.arch.name }}
+    runs-on: ${{ matrix.os.runs-on[matrix.arch.matrix] }}
+    needs:
+    - build
+    strategy:
+      fail-fast: false
+      matrix:
+        os:
+          - name: 11
+            matrix: 11
+            runs-on:
+              intel: macos-11
+              arm: [macos, arm64]
+          - name: 12
+            matrix: 12
+            runs-on:
+              intel: macos-12
+          - name: 13
+            matrix: 13
+            runs-on:
+              intel: macos-13
+        arch:
+          - name: ARM64
+            matrix: arm
+            artifact-name: m1
+          - name: Intel
+            matrix: intel
+            artifact-name: intel
+        exclude:
+          - os:
+              matrix: 12
+            arch:
+              matrix: arm
+          - os:
+              matrix: 13
+            arch:
+              matrix: arm
 
-      - name: Remove working files to exclude from cache
-        run: |
-          rm -rf ./cactus-blockchain-gui/packages/gui/daemon
+    steps:
+    - uses: Cactus-Network/actions/clean-workspace@main
+
+    - name: Download packages
+      uses: actions/download-artifact@v3
+      id: download
+      with:
+        name: cactus-installers-macos-dmg-${{ matrix.arch.artifact-name }}
+        path: packages
+
+    - name: Mount .dmg
+      env:
+        PACKAGE_PATH: ${{ github.workspace }}/build_scripts/final_installer/
+      run: |
+        ls -l "${{ steps.download.outputs.download-path }}"
+        hdiutil attach "${{ steps.download.outputs.download-path }}"/cactus-*.dmg
+
+    - name: Run cactus version
+      run: |
+        "/Volumes/Cactus "*"/Cactus.app/Contents/Resources/app.asar.unpacked/daemon/cactus" version
+
+    - name: Detach .dmg
+      if: always()
+      run: |
+        hdiutil detach -force "/Volumes/Cactus "*
